<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="callMe"
    errors="1" failures="0" hostname="" id="" package="callMe" skipped="0"
    tests="1" time="0.007000" timestamp="Wed, 26 Jul 2017 07:28:59 GMT">
  
    <testcase name="Проверка появления заказа в кабинете клиента" classname="callMe" time="0.007000" assertions="0">
    </testcase>
      <system-err>
          Error while running [Call Me / Проверка появления заказа в кабинете клиента]:

  ReferenceError: prom is not defined
    at Object.module.exports.Проверка появления заказа в кабинете клиента (/home/agent/docs/autotests/nightwatchfs/tests/callMe.js:156:19)
    at Module.call (/home/agent/docs/autotests/nightwatchfs/nightwatch/lib/runner/module.js:62:34)
    at /home/agent/docs/autotests/nightwatchfs/nightwatch/lib/runner/testcase.js:70:29
    at _fulfilled (/home/agent/docs/autotests/nightwatchfs/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/agent/docs/autotests/nightwatchfs/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/agent/docs/autotests/nightwatchfs/node_modules/q/q.js:796:13)
    at /home/agent/docs/autotests/nightwatchfs/node_modules/q/q.js:556:49
    at runSingle (/home/agent/docs/autotests/nightwatchfs/node_modules/q/q.js:137:13)
    at flush (/home/agent/docs/autotests/nightwatchfs/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:419:9)
      </system-err>
  
  
  </testsuite>
</testsuites>
